# Generated by Django 3.0.2 on 2020-01-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
