# Generated by Django 3.0.2 on 2020-01-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep04', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
